{% set name = "param" %}
{% set version = "1.5.1" %}
{% set sha256 = "3f5c771aedc84f342bd9d40b982daef87f0d524e1cdaa1e81d33d40de2025866" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ioam/param/archive/v{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - param

about:
  home: http://ioam.github.io/param/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Param: Make your Python code clearer and more reliable by declaring Parameters'
  description: |
    Param is a library providing Parameters: Python attributes
    extended to have features such as type and range checking,
    dynamically generated values, documentation strings, default
    values, etc., each of which is inherited from parent classes
    if not specified in a subclass.
  doc_url: https://ioam.github.io/param/
  dev_url: https://github.com/ioam/param

extra:
  recipe-maintainers:
    - basnijholt
    - jlstevens
    - philippjfr
