{% set name = "param" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7e2b9c1d308d93c641937330990e8254aef479682c930b36ab681c4587d999a

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python

test:
  imports:
    - param
    - numbergen
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://param.holoviz.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Declarative parameters for robust Python classes and a rich API for reactive programming
  description: |
    Param is a zero-dependency library for declaring rich
    attributes - Parameters - with extended metadata used for
    various purposes such as runtime type and range validation,
    default values or factories, nullability, docstrings, etc.
    It also supplies a suite of reactive APIs (watch, depends,
    bind, and reactive expressions), enabling automatic updates
    on attribute changes and declaring complex reactive
    dependencies and expressions that can be introspected by other
    frameworks to implement their own reactive workflows.
    These capabilities power HoloViz projects like Panel and HoloViews,
    making Param a solid foundation for building validated,
    introspectable, and responsive libraries and applications.
  doc_url: https://param.holoviz.org/
  dev_url: https://github.com/holoviz/param

extra:
  recipe-maintainers:
    - basnijholt
    - jlstevens
    - philippjfr
