travis:
  secure:
    BINSTAR_TOKEN: b1Q9tQ+ZSML6yBgwAqTiP43e7+MxslNEIcOcCYwbE6cqnGQ665Zj49zSP4GtObOBSqcjUqjG9GWPilOBj4ZugQqkju3HueGxLcrccI3+6Hwssd6oPxv/7OZuvLH5VMsW9uK7ZGDAHWTd95ggUV7mSvY3CnyImdvXh0VO/Ndsf1Rxh40n+q5wp0uPAXhYgZx7IfR4GReHkhEhH/pfX8/C8z08tkr06HxPjrcIANlI+3ZhfZkQHibVsLzDT18URA218F2PjoMtLWwRGtXRo5bq26cKjo6o/tgPkSXFpvR9akGtDUvCdIx4PjdCo/SclEj1q/nj7o/KunLmNTG/1y0rPzHMwKxNCKGaw/W9M2UlGyBB5L3K4vS1Fh5gTtcyhcg/xSYuRRyeJOZ6LAF8Jck3OJ+nuLvYDDzlVRtKCxZfe/I/P5tLhgon0A16Sh82Nh2EEmtNT7gqrhjtzm5Bfw3JUSeF/IymNvwd2M9oTevt12KpaGhSHy4RXnV43cmrBVAir/7KK8cWeyGEWxiZDJ1DfGjaBUzSTHPYztLxz9iKmXjsYCYmTUtSwcmbqLKT4NnuUawQhlKPFT6nDQ7qq0uHJ8Ub7sAonkNM7CRZdu7HcZ3Et8GtZlRdiIyZicisj8yMZY9PL7Z2YyQCFCuYguxmA2fk8rK9FYV5wO83+ZKT8RA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
