travis:
  secure:
    BINSTAR_TOKEN: KM6X+VKu0aqkvedeLfoY3eKoXVIR4QcqzTNyH7EOpjRtck66mMK58uGZIROrYYHPkQ72a2tKsmjKZWANp9KgssMQMDVWrMf44LIi/aIiG0wtGnrQ2H3sDHTo7g5cDmctfL6/KNOvhA9ECbigpO1b7i+gNP8dv/1kinU/yUcOIFCjStnmig04J01Q/TbuRFz2nR53OU8J6i8Y+L1tdw9WkeToWV/AkH3CZcL2r9Cw6AYwCs9JOKt+8V+G19kER+xjVZZQJusRAJIdcrYv+bASyyOUPuAVzOWeI9PCNgEdyjMBgWlYqFpRfI3GH3p5vQIak2cD0SJi7ceco6cxElUCYqczn/ZEBByyfq70ODYxWu7N3M6YfUk7Vs6A24/Aag1JIa57NhJI7gyyYZwEN5SMmZViVuYjRIr2Vcb+jsHHvIpIJ7k+WVIuFdzjNypZnRWWfj9r70SqU1QEyI1davcOhc0MpE26Z0jKbeLGkXt2rE++YQZV02ip6Uc+x6UqQ7Ja8v/5Ng7cghshhhU6o1V2wPe3XqcDc9zcoTjlnmg79Y0I4PPzVjVX1kAf07EF0hnNgW78eip7QsZOre0JLcbYTrh4t5v8oJXs7loGRlYHVMZWXfV54CUZWnGeJeCbBokzO8IsevF7rq2iBnfRQj582yoUoOD2GtAvCVNzbHCJGAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
